---
- name: Install Homebrew
  shell: ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  args:
    creates: /usr/local/bin/brew

- name: Update Homebrew
  homebrew: update_homebrew=yes

- name: Create Caskroom
  file:
    path: /opt/homebrew-cask/Caskroom2
    state: directory
    group: staff
    mode: 0755
