---
- name: Install SPF13-Vim
  shell: curl http://j.mp/spf13-vim3 -L -o - | sh
  args:
    creates:
      ~/.spf13-vim-3/

- name: Add single Vim setting
  lineinfile: dest=~/.vimrc.local line="set pastetoggle=<F2>" state=present
